### ISSUE TITLE
Crash in :gradualizer_highlight.parse_into_list_of_forms/1

### ISSUE THREAD

**Issue by lukaszsamson** [josefs/Gradualizer#249]
Gradualizer crashes on latest master (862356582afb4f0e8377111125122c5819c0a7d9) when run on https://github.com/elixir-lsp/elixir_sense project.

Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.4 (compiled with Erlang/OTP 22)

```
Users/elixir_sense/_build/dev/lib/elixir_sense/ebin/Elixir.ElixirSense.Core.Introspection.beam: ** (throw) {:error, '8:12: syntax error before: \'::\''}
    merl.erl:1080: :merl.fail/2
    merl.erl:518: :merl.parse_forms/1
    merl.erl:491: :merl.quote_1/3
    (gradualizer) /Users/elixir_sense/deps/gradualizer/src/gradualizer_highlight.erl:141: :gradualizer_highlight.parse_into_list_of_forms/1
    (gradualizer) /Users/elixir_sense/deps/gradualizer/src/gradualizer_highlight.erl:54: :gradualizer_highlight.recreate_source/2
    (gradualizer) /Users/elixir_sense/deps/gradualizer/src/gradualizer_highlight.erl:36: :gradualizer_highlight.prettyprint_and_highlight/3
    (gradualizer) /Users/elixir_sense/deps/gradualizer/src/gradualizer_fmt.erl:399: :gradualizer_fmt.highlight_in_context/2
    (gradualizer) /Users/elixir_sense/deps/gradualizer/src/gradualizer_fmt.erl:364: :gradualizer_fmt.format_expr_type_error/4
```

**Comment by zuiderkwast** [comment]
Just interpreting the trace and looking up the related line in https://github.com/elixir-lsp/elixir_sense/blob/master/lib/elixir_sense/core/introspection.ex#L32 (I think). It seems `merl:quote/1` doesn't accept a type definition with annotated types inside.

Trying to parse some similar code in Erlang using merl:

```Erlang
1> merl:quote("-type mod_fun() :: {mod :: module() | undefined, 'fun' :: atom() | undefined}.").
** exception throw: {error,"1: syntax error before: '::'"}
     in function  merl:fail/2 (merl.erl, line 1080)
     in call from merl:quote_1/3 (merl.erl, line 491)
```

If i remove the names 'mod' and 'fun', it parses:

```Erlang
2> merl:quote("-type mod_fun() :: {module() | undefined, atom() | undefined}.").                
{attribute,1,type,
           {mod_fun,{type,1,tuple,
                          [{type,1,union,
                                 [{type,1,module,[]},{atom,1,undefined}]},
                           {type,1,union,
                                 [{type,1,atom,[]},{atom,1,undefined}]}]},
                    []}}
```

When I test adding the same type definition in an .erl file and compile it, it's also a syntax error.

I'm starting to wonder: Does Elixir emit abstract code which is fine to the Erlang compiler, but when it's pretty-printed and parsed again as Erlang source code, it's a parse error? It could be possible...

I haven't actually compiled introspection.ex to beam, extracted the abstract code and checked what it contains, so I shouldn't say too much yet.

**Comment by lukaszsamson** [comment]
> Does Elixir emit abstract code which is fine to the Erlang compiler, but when it's pretty-printed and parsed again as Erlang source code, it's a parse error?

AFAIK yes

**Comment by zuiderkwast** [comment]
Interesting!

Then, I guess the only safe way is to have a fallback error formatter which is used if the fancy error highlighter throws an exception. (The fancy error messages rely on pretty-printing.)

**Comment by josefs** [comment]
> > Does Elixir emit abstract code which is fine to the Erlang compiler, but when it's pretty-printed and parsed again as Erlang source code, it's a parse error?
> >
> AFAIK yes
> 

It would be better to solve this issue in gradualixir then. We're not really resourced to tackle Elixir specific problems in gradualizer. I'm inclined to mark this as a "Won't fix".

**Comment by Zalastax** [comment]
What's wrong with @zuiderkwast's idea? It's difficult to fix in gradualixir while the error format is still not unified.

**Comment by josefs** [comment]
There's nothing wrong technically with @zuiderkwast 's idea. But the real question here is whether we can support Elixir or not. Currently we don't have anyone who has stepped up to the role of dealing with Elixir issue for gradualizer. Since that's the case, I think it's easier for everyone to be clear and say that we currently don't fix Elixir problems. But let me be clear, I'd be super-happy to support Elixir, it's just that right now we don't have the bandwidth, and then it's more helpful to be honest about it.

**Comment by zuiderkwast** [comment]
I agree that we shouldn't spend extra time for e.g. for printing errors in Elixir syntax and such. The Elixir users contribute valuable material though and most of the typechecker applies to both languages. We just need to define where to draw the line.

This issue is about abstract code which compiles, but which can't be written in plain Erlang, since the parser rejects it. This kind of abstract code can also be created using a parse transform, so it's not entirely Elixir. (Maybe it could be considered a bug in the Erlang parser?)

I'd like to solve this one using try-catch and fallback to the old error format, which is still there and is used if fancy error messages are disabled. It's a quite simple solution.

**Comment by zuiderkwast** [comment]
Fixed by #252 (hopefully)

**Comment by josefs** [comment]
> I agree that we shouldn't spend extra time for e.g. for printing errors in Elixir syntax and such. The Elixir users contribute valuable material though and most of the typechecker applies to both languages. We just need to define where to draw the line.

Yes, figuring out where to draw the line is the hard part here. We probably shouldn't spend too much energy on this but I'll share some thoughts. 
I argued for drawing it at zero because it's simple and  easy to understand. But we can certainly be a little more nuanced here. A suggestion, based on the fix that you just did, is that we take responsibility for everything that the erlang compiler can accept, be it erlang syntax or erlang absform. But special cases for Elixir syntax/semantics is something that should arguable be handled somewhere else.

**Comment by zuiderkwast** [comment]
OK, it seems we agree. :-)

I was wrong regarding the annotated types though. The annotation needs to be a variable, i.e. starting with a capital. If I change to Mod and Fun the below works fine:

```Erlang
merl:quote("-type mod_fun() :: {Mod :: module() | undefined, Fun :: atom() | undefined}.").
```

So, the problem must have been something else... Anyway, the issue is solved.

**Comment by lukaszsamson** [comment]
@zuiderkwast I tried the latest master and unfortunately it's still broken. The old error forrmat is not written and gradualizer exits. The stacktrace is different now though.
```
/Users/elixir_sense/_build/dev/lib/elixir_sense/ebin/Elixir.ElixirSense.Core.Introspection.beam: ** (throw) {:error, '8:12: syntax error before: \'::\''}
    merl.erl:1080: :merl.fail/2
    merl.erl:518: :merl.parse_forms/1
    merl.erl:491: :merl.quote_1/3
    (gradualizer 0.1.0) /Users/elixir_sense/deps/gradualizer/src/gradualizer_highlight.erl:141: :gradualizer_highlight.parse_into_list_of_forms/1
    (gradualizer 0.1.0) /Users/elixir_sense/deps/gradualizer/src/gradualizer_highlight.erl:54: :gradualizer_highlight.recreate_source/2
    (gradualizer 0.1.0) /Users/elixir_sense/deps/gradualizer/src/gradualizer_highlight.erl:41: :gradualizer_highlight.prettyprint_and_highlight/3
    (gradualizer 0.1.0) /Users/elixir_sense/deps/gradualizer/src/gradualizer_fmt.erl:414: :gradualizer_fmt.highlight_in_context/2
    (gradualizer 0.1.0) /Users/elixir_sense/deps/gradualizer/src/gradualizer_fmt.erl:384: :gradualizer_fmt.try_highlight_in_context/2
```

**Comment by zuiderkwast** [comment]
Oh, that's unfortunate. I was hoping that my try-catch was going prevent these errors. Feel free to debug it further. I can't prioritize it now.

A workaround is to turn off the fancy error messages using an option, `{fancy, false}` if I remember correctly.
